"""
notifier Lambda
ポストモーテムレポートのpresigned URLをAmazon SNSで通知する。

設計意図:
- 通知先はTerraformで作成したSNSトピックに限定する
- エラーモード時は障害通知メッセージを送信
"""

import os
from datetime import datetime, timezone

import boto3
from aws_lambda_powertools import Logger, Tracer
from aws_lambda_powertools.utilities.typing import LambdaContext

logger = Logger()
tracer = Tracer()

sns_client = boto3.client("sns")

SNS_TOPIC_ARN = os.environ["SNS_TOPIC_ARN"]


def _publish_message(subject: str, message: str) -> str:
    """設定済みのSNSトピックへ通知を発行する"""
    response = sns_client.publish(
        TopicArn=SNS_TOPIC_ARN,
        Subject=subject,
        Message=message,
    )
    message_id = response["MessageId"]
    logger.info("SNS送信完了", message_id=message_id)
    return message_id


@logger.inject_lambda_context
@tracer.capture_lambda_handler
def handler(event: dict, context: LambdaContext) -> dict:
    experiment_id = event.get("experiment_id", "unknown")
    is_error_mode = event.get("error_mode", False)

    logger.info("通知処理開始", experiment_id=experiment_id, error_mode=is_error_mode)

    if is_error_mode:
        subject = "[ERROR] ポストモーテムワークフロー失敗"
        message = _build_error_message(experiment_id, event.get("error", {}))
    else:
        subject = "[SUCCESS] Chaos Engineering ポストモーテム完成"
        message = _build_success_message(event)

    message_id = _publish_message(subject, message)
    logger.info("通知完了", experiment_id=experiment_id)

    return {
        "experiment_id": experiment_id,
        "message_id": message_id,
        "notification_sent": True,
        "notification_timestamp": datetime.now(timezone.utc).isoformat(),
    }


def _build_success_message(event: dict) -> str:
    """ポストモーテム生成成功時のSNSメッセージを構築する"""
    experiment_id = event.get("experiment_id", "unknown")
    experiment_type = event.get("experiment_type", "unknown")
    presigned_url = event.get("presigned_url", "")
    postmortem = event.get("postmortem", {})
    summary = postmortem.get("summary", "")
    root_cause = postmortem.get("root_cause", "")
    action_items = postmortem.get("action_items", [])
    duration = event.get("duration_seconds", 0)

    # アクションアイテムを優先度別に整形
    action_lines = []
    for item in action_items[:5]:  # 最大5件表示
        priority = item.get("priority", "medium")
        icon = "🔴" if priority == "high" else "🟡" if priority == "medium" else "🟢"
        action_lines.append(f"{icon} [{priority}] {item.get('task', '')} ({item.get('owner', '')})")

    action_text = "\n".join(action_lines) if action_lines else "なし"

    return f"""🔥 Chaos Engineering ポストモーテム完成
実験ID: {experiment_id}
実験種別: {experiment_type}
障害時間: {duration}秒

【概要】
{summary}

【根本原因】
{root_cause}

【アクションアイテム】
{action_text}

📄 ポストモーテムレポート（7日間有効）:
{presigned_url}

Generated by Amazon Bedrock Claude Sonnet 4.6"""


def _build_error_message(experiment_id: str, error: dict) -> str:
    """ワークフロー失敗時のSNSエラー通知メッセージを構築する"""
    return f"""⚠️ ポストモーテムワークフロー失敗
実験ID: {experiment_id}
エラー: {error.get("Error", "unknown")}
原因: {error.get("Cause", "unknown")}
発生時刻: {datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")}

対応: AWSコンソールのStep Functions実行履歴を確認してください。"""
