"""
notifier Lambda
ポストモーテムレポートのpresigned URLをChatwork APIで通知する。

設計意図:
- Chatwork APIキーはSecrets Managerから取得（ハードコード禁止）
- api_key と room_id を1つのシークレットで管理
- Slack不使用（CLAUDE.md設計方針）
- エラーモード時は障害通知メッセージを送信
- Lambda実行ライフサイクル内でシークレットをキャッシュして重複呼び出しを防ぐ
"""

import json
import os
import urllib.parse
import urllib.request
from datetime import datetime, timezone

import boto3
from aws_lambda_powertools import Logger, Tracer
from aws_lambda_powertools.utilities.typing import LambdaContext

logger = Logger()
tracer = Tracer()

secrets_client = boto3.client("secretsmanager")

PROJECT_NAME = os.environ.get("PROJECT_NAME", "eks-chaos-postmortem-generator")
ENVIRONMENT = os.environ.get("ENVIRONMENT", "dev")

# シークレット名: eks-chaos-postmortem/chatwork-api-key-dev
SECRET_NAME = f"{PROJECT_NAME}/chatwork-api-key-{ENVIRONMENT}"

# Lambda実行ライフサイクル内でキャッシュ（ウォームスタート時の再取得を防ぐ）
_secret_cache: dict | None = None


def _get_chatwork_credentials() -> dict:
    """Secrets ManagerからChatwork APIキーとルームIDを取得する"""
    global _secret_cache
    if _secret_cache:
        return _secret_cache

    response = secrets_client.get_secret_value(SecretId=SECRET_NAME)
    _secret_cache = json.loads(response["SecretString"])
    return _secret_cache


def _send_chatwork_message(room_id: str, api_key: str, message: str) -> None:
    """Chatwork API v2でメッセージを送信する"""
    url = f"https://api.chatwork.com/v2/rooms/{room_id}/messages"
    data = urllib.parse.urlencode({"body": message}).encode("utf-8")

    req = urllib.request.Request(url, data=data, method="POST")
    req.add_header("X-ChatWorkToken", api_key)
    req.add_header("Content-Type", "application/x-www-form-urlencoded")

    with urllib.request.urlopen(req, timeout=10) as response:
        result = json.loads(response.read())
        logger.info("Chatwork送信完了", message_id=result.get("message_id"))


@logger.inject_lambda_context
@tracer.capture_lambda_handler
def handler(event: dict, context: LambdaContext) -> dict:
    experiment_id = event.get("experiment_id", "unknown")
    is_error_mode = event.get("error_mode", False)

    logger.info("通知処理開始", experiment_id=experiment_id, error_mode=is_error_mode)

    try:
        credentials = _get_chatwork_credentials()
    except Exception as e:
        logger.error("Chatwork認証情報取得失敗", error=str(e))
        raise

    api_key = credentials.get("api_key", "")
    room_id = credentials.get("room_id", "")

    if not room_id:
        logger.warning("room_idが未設定のため通知をスキップします")
        return {"statusCode": 200, "body": "skipped_no_room_id"}

    if is_error_mode:
        message = _build_error_message(experiment_id, event.get("error", {}))
    else:
        message = _build_success_message(event)

    _send_chatwork_message(room_id, api_key, message)
    logger.info("通知完了", experiment_id=experiment_id)

    return {
        "experiment_id": experiment_id,
        "notification_sent": True,
        "notification_timestamp": datetime.now(timezone.utc).isoformat(),
    }


def _build_success_message(event: dict) -> str:
    """ポストモーテム生成成功時のChatworkメッセージを構築する"""
    experiment_id = event.get("experiment_id", "unknown")
    experiment_type = event.get("experiment_type", "unknown")
    presigned_url = event.get("presigned_url", "")
    postmortem = event.get("postmortem", {})
    summary = postmortem.get("summary", "")
    root_cause = postmortem.get("root_cause", "")
    action_items = postmortem.get("action_items", [])
    duration = event.get("duration_seconds", 0)

    # アクションアイテムを優先度別に整形
    action_lines = []
    for item in action_items[:5]:  # 最大5件表示
        priority = item.get("priority", "medium")
        icon = "🔴" if priority == "high" else "🟡" if priority == "medium" else "🟢"
        action_lines.append(f"{icon} [{priority}] {item.get('description', '')} ({item.get('owner', '')})")

    action_text = "\n".join(action_lines) if action_lines else "なし"

    return f"""[info][title]🔥 Chaos Engineering ポストモーテム完成[/title]
実験ID: {experiment_id}
実験種別: {experiment_type}
障害時間: {duration}秒

【概要】
{summary}

【根本原因】
{root_cause}

【アクションアイテム】
{action_text}

📄 ポストモーテムレポート（7日間有効）:
{presigned_url}

Generated by Amazon Bedrock Claude Sonnet 3.5
[/info]"""


def _build_error_message(experiment_id: str, error: dict) -> str:
    """ワークフロー失敗時のChatworkエラー通知メッセージを構築する"""
    return f"""[info][title]⚠️ ポストモーテムワークフロー失敗[/title]
実験ID: {experiment_id}
エラー: {error.get("Error", "unknown")}
原因: {error.get("Cause", "unknown")}
発生時刻: {datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")}

対応: AWSコンソールのStep Functions実行履歴を確認してください。
[/info]"""
