all:
  vars:
    ansible_user: ec2-user
    ansible_ssh_private_key_file: /home/takuya/terraform-lab/zabbix-lab/terraform/envs/dev/.ssh/zabbix_lab_key
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
  children:
    zabbix_server:
      hosts:
        zabbix-server:
          ansible_host: 54.248.69.6
          private_ip: 10.10.1.18
    targets:
      hosts:
        target-01:
          ansible_host: 52.68.152.215
          private_ip: 10.10.1.124
