module "vpc" {
  source = "../../modules/vpc"
  name   = var.name
}

# --- SSH keypair generated by Terraform (plan時点で確定するので安全) ---
resource "tls_private_key" "ssh" {
  algorithm = "ED25519"
}

resource "local_file" "ssh_private_key" {
  filename        = "${path.module}/.ssh/zabbix_lab_key"
  content         = tls_private_key.ssh.private_key_openssh
  file_permission = "0600"
}

resource "local_file" "ssh_public_key" {
  filename        = "${path.module}/.ssh/zabbix_lab_key.pub"
  content         = tls_private_key.ssh.public_key_openssh
  file_permission = "0644"
}

resource "aws_key_pair" "this" {
  key_name   = var.ssh_key_name
  public_key = tls_private_key.ssh.public_key_openssh
}

module "ec2" {
  source = "../../modules/ec2"

  name                 = var.name
  vpc_id               = module.vpc.vpc_id
  subnet_id            = module.vpc.public_subnet_id
  my_ip_cidr           = var.my_ip_cidr
  key_name             = aws_key_pair.this.key_name
  instance_type_server = var.instance_type_server
  instance_type_target = var.instance_type_target
}
