"""
Bedrockが生成したHCLコードを整形・検証するモジュール
"""

import re
from datetime import datetime, timezone


def validate_and_format_hcl(raw_hcl: str) -> str:
    """
    BedrockのHCL出力を検証・整形する。
    マークダウンコードブロックの除去、括弧バランスチェックを行う。
    """
    # マークダウンコードブロック (```hcl ... ``` や ``` ... ```) を除去
    hcl = re.sub(r"^```(?:hcl)?\s*\n?", "", raw_hcl.strip(), flags=re.MULTILINE)
    hcl = re.sub(r"\n?```\s*$", "", hcl.strip(), flags=re.MULTILINE)
    hcl = hcl.strip()

    # "resource" キーワードの存在確認（Bedrockが非HCLテキストを返した場合の防御）
    if "resource" not in hcl:
        raise ValueError("HCLに 'resource' キーワードが含まれていません。Bedrockの出力が不正です。")

    # 基本的な括弧バランスチェック
    open_count = hcl.count("{")
    close_count = hcl.count("}")
    if open_count != close_count:
        raise ValueError(
            f"HCLの括弧バランスが不正です。開き括弧: {open_count}, 閉じ括弧: {close_count}"
        )

    return hcl


def add_drift_fix_header(hcl: str, analysis_result: dict) -> str:
    """
    HCLファイルの先頭にコメントヘッダーを付与する。
    AIが生成したファイルであることを明示し、手動レビューを促す。
    """
    timestamp = datetime.now(timezone.utc).isoformat()
    severity = analysis_result.get("severity", "UNKNOWN")
    drift_summary = analysis_result.get("drift_summary", "")

    header = f"""# ============================================================
# Drift Fix - Auto-generated by IaC Drift Detective
# Generated: {timestamp}
# Severity: {severity}
# Summary: {drift_summary}
# WARNING: このファイルはAIが生成しました。
#          terraform plan で差分を確認してから apply してください。
# ============================================================

"""
    return header + hcl
