apiVersion: v1
kind: Service
metadata:
  name: sample-app
  namespace: perf-tuning
  labels:
    app: sample-app
spec:
  selector:
    app: sample-app
  ports:
    - name: http
      port: 80
      targetPort: 8080
    - name: metrics
      port: 9090
      targetPort: 8080
  type: ClusterIP
