//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.
// controller-gen で自動生成されるファイル。手動編集不可。
// `make generate` で再生成すること。

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto は AIInferenceService の全フィールドをディープコピーする
func (in *AIInferenceService) DeepCopyInto(out *AIInferenceService) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy は AIInferenceService の完全なコピーを返す
func (in *AIInferenceService) DeepCopy() *AIInferenceService {
	if in == nil {
		return nil
	}
	out := new(AIInferenceService)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject は runtime.Object インターフェースを実装する
func (in *AIInferenceService) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto は AIInferenceServiceList の全フィールドをディープコピーする
func (in *AIInferenceServiceList) DeepCopyInto(out *AIInferenceServiceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AIInferenceService, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy は AIInferenceServiceList の完全なコピーを返す
func (in *AIInferenceServiceList) DeepCopy() *AIInferenceServiceList {
	if in == nil {
		return nil
	}
	out := new(AIInferenceServiceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject は runtime.Object インターフェースを実装する
func (in *AIInferenceServiceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto は AIInferenceServiceSpec の全フィールドをディープコピーする
func (in *AIInferenceServiceSpec) DeepCopyInto(out *AIInferenceServiceSpec) {
	*out = *in
	out.ScalingMetric = in.ScalingMetric
	if in.BedrockFallback != nil {
		in, out := &in.BedrockFallback, &out.BedrockFallback
		*out = new(BedrockFallback)
		**out = **in
	}
	if in.SelfHealing != nil {
		in, out := &in.SelfHealing, &out.SelfHealing
		*out = new(SelfHealing)
		**out = **in
	}
}

// DeepCopy は AIInferenceServiceSpec の完全なコピーを返す
func (in *AIInferenceServiceSpec) DeepCopy() *AIInferenceServiceSpec {
	if in == nil {
		return nil
	}
	out := new(AIInferenceServiceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto は AIInferenceServiceStatus の全フィールドをディープコピーする
func (in *AIInferenceServiceStatus) DeepCopyInto(out *AIInferenceServiceStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastScaleTime != nil {
		in, out := &in.LastScaleTime, &out.LastScaleTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy は AIInferenceServiceStatus の完全なコピーを返す
func (in *AIInferenceServiceStatus) DeepCopy() *AIInferenceServiceStatus {
	if in == nil {
		return nil
	}
	out := new(AIInferenceServiceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto は BedrockFallback の全フィールドをディープコピーする
func (in *BedrockFallback) DeepCopyInto(out *BedrockFallback) {
	*out = *in
}

// DeepCopy は BedrockFallback の完全なコピーを返す
func (in *BedrockFallback) DeepCopy() *BedrockFallback {
	if in == nil {
		return nil
	}
	out := new(BedrockFallback)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto は ScalingMetric の全フィールドをディープコピーする
func (in *ScalingMetric) DeepCopyInto(out *ScalingMetric) {
	*out = *in
}

// DeepCopy は ScalingMetric の完全なコピーを返す
func (in *ScalingMetric) DeepCopy() *ScalingMetric {
	if in == nil {
		return nil
	}
	out := new(ScalingMetric)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto は SelfHealing の全フィールドをディープコピーする
func (in *SelfHealing) DeepCopyInto(out *SelfHealing) {
	*out = *in
}

// DeepCopy は SelfHealing の完全なコピーを返す
func (in *SelfHealing) DeepCopy() *SelfHealing {
	if in == nil {
		return nil
	}
	out := new(SelfHealing)
	in.DeepCopyInto(out)
	return out
}
